### ISSUE TITLE
Conflict with add-on 'Absolute Enable Right Click and Copy'

### ISSUE THREAD

**Issue by streetwolf** [asamuzaK/url2clipboard#58] opened 2018-08-20 18:12 UTC
The quick menu does not appear on certain sites with the add-on mentioned.  An example page is https://www.msn.com/en-us/news/world/mysterious-giant-shark-spotted-in-rare-sighting/ar-BBMaIx3?li=BBnba9K.  This issue probably happens on any page that disables right click.

Add-on can be found here... https://addons.mozilla.org/en-US/firefox/user/Absolute-Ex/

**Comment by asamuzaK** [comment] 2018-08-20 20:46
I created a test page, but can't reproduce

1. Disable `Absolute Enable Right Click & Copy`
2. Go to http://asamuzak.jp/test/right-click
3. Right click somewhere and make sure context menu does not show up
4. Enable `Absolute Enable Right Click & Copy`
5. Right click somewhere again, then context menu *does* shows up on my environment

**Comment by streetwolf** [comment] 2018-08-20 20:49
Doesn’t work with me.  Forget to mention I’m on the latest Fx Nightly.

-----
Gary

________________________________

**Comment by asamuzaK** [comment] 2018-08-20 20:59
Please test with a clean profile?

**Comment by asamuzaK** [comment] 2018-08-20 21:01
Also check error logs in `Ctrl + Shift + J` and `Ctrl + Shift + K`.

**Comment by streetwolf** [comment] 2018-08-20 21:09
My bad.  It is another add-on that conflicts with AERC&C not yours.  So very sorry.

-----
Gary

________________________________

**Comment by asamuzaK** [comment] 2018-08-20 21:11
No worries
Closing

**Closed by asamuzaK** 2018-08-20 21:11 UTC

**Comment by Klipperken** [comment] 2024-02-11 15:25
Hail:

Absolute Enable Right Click and Copy causes a strange behavior in MSEdge and firefox (Win 11 Ent), while in google.
When entering with this extension enabled ... I get a new line, instead of actually starting the search.

Now, I use this extension quite frequently, so, I would like to see this issue fixed.

Or is there another solution, please?

Thank you:
Klip
