### ISSUE TITLE
url2clipboard not in context menu

### ISSUE THREAD

**Issue by Sensor66** [asamuzaK/url2clipboard#135] opened 2023-02-16 09:37 UTC
Dear asamuzaK,
I am a daily user of your FF extension. Suddenly, today, the entry in the context menu of FF is not visible. I tried to re-start FF, disable and restart url2clipboard , but to no avail.
Thanks!
Sensor66

**Comment by asamuzaK** [comment] 2023-02-16 14:27
Maybe dupe of [Version 9.3.2 not working · Issue #134](https://github.com/asamuzaK/url2clipboard/issues/134 "Version 9.3.2 not working · Issue #134 · asamuzaK/url2clipboard")?
Try v9.3.3 and reopen if issue still exists.

**Closed by asamuzaK** 2023-02-16 14:27 UTC
