### ISSUE TITLE
Option to automatically substitute one character for another in the title?

### ISSUE THREAD

**Issue by mwoffenden** [asamuzaK/url2clipboard#73] opened 2019-05-17 14:00 UTC
We use Copy URL To Clipboard _dozens_ of times each day to copy links to paste into Jira and Confluence.

While it works great most of the time, URL titles that contain the "|" character are a problem for Jira because Jira uses the "|" as a divider between the title and URL.

Is it possible to have a configurable option to automagically substitute one character for another?  In this case we would love to see "|" automatically replaced by "-", but this should be configurable by the user.

**Comment by asamuzaK** [comment] 2019-05-17 15:32
This issue was already apparent when we dealt with the Jira format.
See [Need format for JIRA · Issue #37 · asamuzaK/url2clipboard](https://github.com/asamuzaK/url2clipboard/issues/37)

Since this is a bug in Jira itself, I think you should contact Jira's developers and report that the link will not be created correctly if the brackets and/or pipes `[] |` are included in the text content.

**Comment by asamuzaK** [comment] 2019-05-17 15:43
And for text replacement, it looks like that there are some addons for renaming document title (not tested myself):

* [Rename Tab Title](https://addons.mozilla.org/firefox/addon/rename-tab-title/)
* [Tab ReTitle](https://addons.mozilla.org/firefox/addon/tab-retitle/)
* [Rename Tab Title of Domain/URL](https://addons.mozilla.org/firefox/addon/rename-tab-title-of-domain-url/)

**Comment by mwoffenden** [comment] 2019-05-17 18:33
> This issue was already apparent when we dealt with the Jira format.
> See [Need format for JIRA · Issue #37 · asamuzaK/url2clipboard](https://github.com/asamuzaK/url2clipboard/issues/37)
> 
> Since this is a bug in Jira itself, I think you should contact Jira's developers and report that the link will not be created correctly if the brackets and/or pipes `[] |` are included in the text content.

Ok, will report this issue to Atlassian.

**Comment by asamuzaK** [comment] 2019-05-17 22:36
Then let's treat this issue as a duplicate of #72
I don't intend to implement this feature myself, but I'll accept a PR.

**Closed by asamuzaK** 2019-05-17 22:36 UTC
Labels: duplicate

**Comment by asamuzaK** [comment] 2019-07-10 02:04
> Ok, will report this issue to Atlassian.

BTW, where is this issue tracked?
